services:
  nginx:
    image: nginx:1.25-alpine
    container_name: taskmanager_nginx
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
    volumes:
      - ./docker/nginx/dev/conf.d:/etc/nginx/conf.d
      - ./backend:/var/www/backend
      - ./frontend:/var/www/frontend
      # - ./docker/nginx/dev/ssl:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - taskmanager_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: taskmanager_php
    volumes:
      - ./backend:/var/www/backend
      # - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      DATABASE_URL: "${DATABASE_URL:-mysql://taskuser:taskpass@mysql:3306/taskmanager?serverVersion=8.0&charset=utf8mb4}"
      JWT_SECRET: "${JWT_SECRET:-ChangeThisJWTSecretKey}"
      APP_ENV: "dev"
      APP_DEBUG: "1"
    networks:
      - taskmanager_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: taskmanager_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - taskmanager_network

  # PHPMyAdmin (опционально)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: taskmanager_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: taskuser
      PMA_PASSWORD: taskpass
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - taskmanager_network

volumes:
  mysql_data:

networks:
  taskmanager_network:
    driver: bridge