nelmio_cors:
    defaults:
        origin_regex: true
        # allow_origin: ['*']
        allow_origin: ['http://localhost:3000']  # Явно указываем фронтенд
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['*']
        # expose_headers: ['*']
        max_age: 3600
        allow_credentials: true  # 🔑 КРИТИЧЕСКИ ВАЖНО!
    paths:
        '^/': null
